version: "3.7"
services:
    db:
        build:
            context: ./mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - 3306:3306
        volumes:
            - ../../data/mariadb/var:/var/lib/mysql
            - ../../data/mariadb/conf.d:/etc/mysql/conf.d
        networks:
          - internal_network

    web:
        build:
            context: ./server
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - ./server/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ../../data/nginx/logs:/etc/nginx/logs
            - ../../data/nginx/letsencrypt/etc:/etc/letsencrypt
            - ../../data/nginx/letsencrypt/var:/var/lib/letsencrypt
            - ../../var/www:/var/www
        networks:
            - internal_network

networks:
  internal_network:
